name: Moostrap

web: "[http://holyshared.github.com/Moostrap](http://holyshared.github.com/Moostrap)"

description: "Moostrap offers the initialization function of large-scale application from middle-scale."

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://sharedhat.com/mit-license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - Source/Core/Moostrap.js
  - Source/Executer/Executer.js
  - Source/Executer/Async.js
  - Source/Executer/Sync.js

author: holyshared

category: Utilities

tags: [bootstrap, setup]

current: 1.1.2

#docs: http://url_to_plugin_docs

demo: http://holyshared.github.com/Moostrap/
