name: Bootstrap

web: "[http://holyshared.github.com/Bootstrap](http://holyshared.github.com/Bootstrap)"

description: 

authors: "[Noritaka Horio](http://sharedhat.com)"

license: "[MIT License](http://sharedhat.com/mit-license.txt)"

copyright: "&copy; [Noritaka Horio](http://sharedhat.com)"

sources:
  - Source/Core/Bootstrap.js
  - Source/Executer/Executer.js
  - Source/Executer/Async.js
  - Source/Executer/Sync.js

author: holyshared

category: Utilities

tags: [bootstrap, setup]

current: 1.0

#docs: http://url_to_plugin_docs

demo: http://holyshared.github.com/Bootstrap/